### ISSUE TITLE
Make the package better

### ISSUE THREAD

**Issue by MandiYang** [looking-for-a-job/connection.py#1]
I have a good idea for making the package better by editing the __init__.py to this:

    import requests

    TIMEOUT = 5
    URL='http://www.google.com/'

    def check(timeout=None, url=None):
        """return True if connection is ok, else False"""
        if not timeout:
            timeout = TIMEOUT
        if not url:
            url=URL
        try:
            requests.get(url=URL, timeout=timeout)
            return True
        except requests.ConnectionError:
            return False
        except requests.exceptions.ReadTimeout:
            False
        return False

Then you can choose url to fetch and the default url is still 'http://www.google.com/' so you can check connection to other urls!

**Comment by andrewpetrochenkov** [comment]
done. thx

**Comment by MandiYang** [comment]
UPGRADE, make the package better and fixed some misstakes of my code:

    __all__ = ['check']


    import requests

    TIMEOUT = 5
    URL = 'http://www.google.com/'


    def check(timeout=None, url=None):
        """return True if connection is ok, else False"""
        if not timeout:
            timeout = TIMEOUT
        if not url:
            url = URL
        try:
            requests.get(url=url, timeout=timeout)
            return True
        except requests.ConnectionError:
            return False
        except requests.exceptions.ReadTimeout:
            False
        except requests.exceptions.MissingSchema:
            print("URL doesnt exist")
        return False
